export default {
  TICK: 'TICK',
  ADD: 'ADD',

  SET_USER_PROFILE: 'SET_USER_PROFILE',

  SET_QUESTIONS: 'SET_QUESTIONS',
  SET_FILTERS: 'SET_FILTERS',

  PUSH_NOTIFICATION: 'PUSH_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
};
